### ISSUE TITLE
Trigger alarms from dashboard

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#116]
Dashboard can contain graphs of certain metrics over time. Given a threshold it would nice to be able to trigger some "alarm" if a metric falls below its threshold.

**Comment by paulinshek** [comment]
We still need to flesh out what exactly we mean by an "alarm". 

Possibilities: 

* Send an email
* Integrate with ECOMP (?) api to create a browser notification?

**Comment by gaborcsardi** [comment]
This is done as I understand.
