### ISSUE TITLE
Grid items on some pages don't render when displayed

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#117]
This does not happen for the first page, but it does for all successive pages.

**Comment by NattyE** [comment]
This could possibly be linked to https://github.com/att/rcloud.rcap/issues/98

**Comment by paulinshek** [comment]
Sorry, not just htmlwidgets.. i just meant grid items- will change the title so that it's less missleading!

**Comment by paulinshek** [comment]
(I think it is an R issue related to the dag- but I might be wrong!)

**Comment by shaneporter** [comment]
What's the difference between rendering and displaying? Do you mean they aren't shown when the page they are on is made the 'active' page? Does this apply to all controls?

**Comment by paulinshek** [comment]
Yes and, I think just all the R controls. 

Workarounds:

* click on all the pages before the first page has finished loading
* trigger a change to get a specific item to be shown

**Comment by gaborcsardi** [comment]
I am pretty sure this was only htmlwidgets, and that is fixed now. 

Otherwise will reopen this issue.
