### ISSUE TITLE
installing sparklines

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#119]
Currently sparklines is not installed automatically:

when we use `bower install` this installs the sparklines library in lots of separate js files. To use the .min.js file, we need to also navigator the that directory and `make`.

This also has the additional dependencies:

uglifyjs

We need to fully automate this.

**Comment by gaborcsardi** [comment]
Will handle this after #4 is done, that changes the build process entirely.

**Comment by gaborcsardi** [comment]
Fixed by the new build process.
