### ISSUE TITLE
Multiple selected values do not work with the multi select control

### ISSUE THREAD

**Issue by NattyE** [att/rcloud.rcap#136]
They do work with checkbox groups (not with the multi select control).

**Comment by NattyE** [comment]
This should work as described by the Wiki entry: https://github.com/att/rcloud.rcap/wiki/Defining-default-selected-values-for-form-controls

**Comment by shaneporter** [comment]
This issue was found whilst developing an implementation for #32, but was found to be a pre-existing issue.

**Comment by shaneporter** [comment]
Resolved with PR #137.
