### ISSUE TITLE
The RCAP DataTable widget nolonger works when there is a “.” in the column name. 

### ISSUE THREAD

**Issue by robert-a** [att/rcloud.rcap#145]
The RCAP DataTable widget nolonger works when there is a “.” in the column name. This is a significant error as this situation is very common! 

It generates a js alert and the column is blank. If a number follows the ".", it instead shows the single character of each cell value, indexed by that number.

**Comment by shaneporter** [comment]
This issue was introduced with release 0.3.4 - working on tracking down exactly what caused it.

**Comment by shaneporter** [comment]
Fixed in PR #151.
