### ISSUE TITLE
RCAP controls are not using the initial values

### ISSUE THREAD

**Issue by robert-a** [att/rcloud.rcap#146]
RCAP controls (e.g., dropdown, radio button, datepicker) are not using the initial values that are set in the notebook (e.g., rcap_var1 <<- "myvalue";)

**Comment by NattyE** [comment]
Hi @robert-a can you give us a reproducible example? This seems to be working for myself, see this notebook: b33af1bfbcb0f9ab92b248fb9fd3f59f

**Comment by robert-a** [comment]
I can no longer reproduce the problem in an example notebook, so I agree it seems to be working. I am seeing a problem with the Radio buttons in some complex notebooks, but I will have to study it further.
