### ISSUE TITLE
Under RCAP designer, message is not getting displayed

### ISSUE THREAD

**Issue by amithrb** [att/rcloud.rcap#155]
For RCAP designer page, background message is not shown when we open the RCAP designer for second time for empty page.
Message is shown when we reload the url or restart the rcloud.

Steps to Reproduce:
- Open rcloud
- Create new notebook
- Open RCAP designer. Following message is displayed
![capture](https://cloud.githubusercontent.com/assets/19602717/18741455/f2a25a6c-80cc-11e6-8bff-a7f6b2c790c1.PNG)
- Close the RCAP designer 
- Once again open the RCAP designer. Message is not getting displayed. Following is the screenshot
![capture](https://cloud.githubusercontent.com/assets/19602717/18741519/51e72ffc-80cd-11e6-8428-74e243e819fd.PNG)

**Comment by shaneporter** [comment]
The 'this page is empty' message also fails to appear when adding a new page.
