### ISSUE TITLE
R package dashboard themes

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#162]
Support themes using standard R packages.

RCAP will query installed R packages with the name format _**rcloud.rcap.style.***_. 

An OCAP will be added so that the designer can retrieve this information and list it in a dropdown. The selected package (if any) will be saved in the `rcap_designer.json` file.

The theme package will contain a CSS file which will be dynamically loaded at design/view time.

If a specified theme is not found, a warning message will appear in the designer; a console warning message will be output in the viewer.

@gaborcsardi - would be nice to add some optional information in the package that could be displayed in the designer, such as the description.

**Comment by gaborcsardi** [comment]
Here are two examples:
https://github.com/MangoTheCat/rcloud.rcap.style.att
https://github.com/MangoTheCat/rcloud.rcap.style.bragi

**Comment by gaborcsardi** [comment]
> @gaborcsardi - would be nice to add some optional information in the package that could be displayed in the designer, such as the description.

You can just put this in the `DESCRIPTION` file of the package, in the `Title` and `Description` fields.
