### ISSUE TITLE
Radio Button default value not shown

### ISSUE THREAD

**Issue by robert-a** [att/rcloud.rcap#180]
The default value of the radio button control is not shown as selected unless using TRUE or FALSE. This happens whether the default value of the  variable is set or the selected= option is used.

**Comment by shaneporter** [comment]
I have tested this and found that it does work in the `selected=` option scenario (using the `getVals` function), but only if the `selected=` option has a single value:

```r
getVals <<- function(){
  list(value = c("potatoes", "tomatoes", "plums"),
      selected = c("plums"))
      #selected = c("plums", "tomatoes"))
}
```

using "plums" and "tomatoes" has no affect on the radio buttons and they are all unselected
