### ISSUE TITLE
Option to show radio/checkbox button to the left of the label

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#187]

**Comment by shaneporter** [comment]
Whilst fixing #186, I was surprised to see radio buttons and checkboxes with their labels to the left of the control. I'm not sure why this was the case, or why I hadn't noticed it before, but it's [not the standard approach](http://ux.stackexchange.com/a/9611) for LTR languages.

The change for #186 will affect existing RCAP websites of course; I just want to check whether the 'flip' option for label orientation is still required.

**Comment by robert-a** [comment]
I agree, stay with the standard of the value label to the right. The flip option is not necessary.

**Comment by shaneporter** [comment]
Thanks @robert-a, closing.
