### ISSUE TITLE
RCAP doesn't function for historical notebooks

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#214]
Attempted to open RCAP on historical notebook (that happened to have no `rcap_designer.json` asset) and several errors were thrown.

Not tested historical version _with_ `rcap_designer.json` but since historical versions are read-only, it wouldn't be appropriate to invoke the RCAP interface anyway.

**Comment by robert-a** [comment]
What is a "historical notebook"? It isn't an RCAP notebook without the rcap_designer.json asset.

**Comment by shaneporter** [comment]
A historical notebook is a previous version of a notebook. You see 'historical versions' by clicking on the 'history' icon for a particular notebook in the notebook tree.

I can't recall seeing this issue before, and only came across it today by accident.

**Comment by shaneporter** [comment]
Related to #66
