### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#224]
### Overview

Dashboard designers should be able to add 'profile support' for specific notebooks and data. Logged in dashboard viewers will be able to configure the data they see.

The designer will have a new 'Profile' toolbar button, which will show a dialog with all the dashboard's variables.  The designer user will be able to give each variable a description (_regions_ - US regions, for example).

A new control, 'Profile' will also be added to the toolbox. When the dashboard runs, the viewer user can click on this control to configure their data.

The data for each variable (alongside its description, set by the dashboard designer user) will be presented to the user, allowing them to choose their own, personalised values. This data will be stored (implementation to be discussed) against the RCloud instance, notebook and user id.

### For the notebook developer

Current form controls' values are populated by functions. Profile support will make available to notebook developers a `getUserProfileValue` function:

```R
rcap.getUserProfileValue(var="region", val=NULL)
```
- var the variable desired (not it’s Label)
- val a vector of the default values 

If var is not found in the User’s profile, val is returned.
If var is found:
 -- if val is not NULL, the intersection of the User’s var selection & val will be returned. 
 -- If val is NULL, the User’s var selection will be returned. 

```R
RegionDropdown <<- function() {   
  return( c( “All”, rcap.getUserProfileValue(var=‘region’, val=getRegions()) ) )
}
```

The notebook designer should handle the case where there is no valid selection (the data doesn't include any values the user has previously selected).

**Comment by useless5771** [comment]
Note: the ticket just specifies a 'public' API of the profile.  Internally full CRUD for profile variables is needed.

Namely (all ops for targetted on triplet: notebook, dashboard id, user id):
* set
* update
* delete
* get
* list all variables associated with notebook and design id.
Plus, event handlers:
* delete variables associated with rcap design file if it gets deleted
* what about updated designs? What should happen with already persisted variables? should rcap read all profiled variables on load and remove any which are not relevant any more? 
*

**Comment by shaneporter** [comment]
Interesting question about removal of redundant variable data. Perhaps it should be ignored as a first version.
