### ISSUE TITLE
Add 'RCAP Viewer' item to RCloud advanced menu

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#256]
Quite often, I'll open an RCAP notebook in RCloud and want to view its output rather than its design.

So, rather than clicking on 'RCAP Designer', and then another click, I'd prefer to have a 'RCAP Viewer' link so I can view the dashboard in the quickest and most convenient way.

**Comment by gordonwoodhull** [comment]
What's the difference between this feature and the "shareable link" at the left of the RCloud navbar?

![image](https://user-images.githubusercontent.com/1366709/29277054-8c4ad2f4-80de-11e7-8ed9-4c7b7f742ed4.png)

**Comment by robert-a** [comment]
Use the “rcap.html” viewer under the sharable link button.

**Comment by shaneporter** [comment]
First day back after being away for a while. No, no. I have no excuse to forgetting about the shareable link.

:)
