### ISSUE TITLE
Color selection for controls

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#33]
Add the ability to enter the color number (#FFFF00) or name (skyblue) rather than clicking on the color grids. The code for the color selected should be displayed in the color selection pop up box. This would make it easier to get the exact color desired or replicate a color used elsewhere.

**Comment by paulinshek** [comment]
So, I've had a play around, but I've not been able to get it working- can not make it possible to focus on the input text box, unfortunately.

Things that I've tried: 
* overwriting _allowInteraction
* using the append option when initialising spectrum
