### ISSUE TITLE
don't send builds to /data/rcloud

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rcloud.rcap#4]
This is a known problem, just entering it here because it's one of the blockers for a public release of RCAP.

Since I have to build packages as myself and then install them as someone else, I've been patching the gruntfile to build the .tar.gz (`R CMD build` step) to my home directory. 

Then I install it manually (`R CMD INSTALL` step).

I'm not sure what the idiomatic grunt thing is. Maybe creating an output directory within the project directory would be simplest. 

There is no particular reason to build to rcloud.packages, nothing special about that directory. There also isn't much magic in `build_packages.sh` except that it pulls the version out of the `DESCRIPTION` file so that it knows what file to `R CMD INSTALL`.

So we could have two targets, one which just builds the package and one which also installs it.

**Comment by gaborcsardi** [comment]
I am happy to fix this, once we decide on how. :)

**Comment by gordonwoodhull** [comment]
My understanding is that we just want a DESCRIPTION in the root directory and we want either `R CMD mkdist` or `build` to work. This will make the package compatible with rforge.net.

It sounds like it works well enough with `install_github`; the objective is to have it work with `install.packages` too. And rforge.net is good enough, we don't really need CRAN.

Does this make sense?

**Comment by gaborcsardi** [comment]
Yes. `install.package` won't work on the GH repo, though. It will probably work on the releases.

Do we want to put the package on rforge.net?

**Comment by gordonwoodhull** [comment]
Yes, we generally use rforge as our distribution mechanism for RCloud-specific packages.

**Comment by gaborcsardi** [comment]
Have a PR for this in #124

**Comment by gaborcsardi** [comment]
PR #124 merged.

**Comment by gordonwoodhull** [comment]
@gaborcsardi, am I correct that we still don't have a way to do an automated build of rcloud.rcap - only the github releases work? Thanks.

**Comment by gaborcsardi** [comment]
No, there is a way, see the README: https://github.com/att/rcloud.rcap#installation

```r
devtools::install_github("att/rcloud.rcap", local = FALSE)
```

Obviously, you need a bunch of tools for this, because it will build locally. E.g. node.js, npm, bower, grunt and GNU make.

**Comment by gordonwoodhull** [comment]
I tried that but it failed earlier than the tools:

```
Downloading GitHub repo att/rcloud.rcap@master
Error: Does not appear to be an R package (no DESCRIPTION)
```

**Comment by gaborcsardi** [comment]
Indeed, because we use the `develop` branch, I am not sure why, actually. I'll fix the README in a sec:

```
devtools::install_github("att/rcloud.rcap@develop", local = FALSE)
```

It takes a while to run, and the R installer does not allow any output, so wait a minute when you see 
`* running ‘cleanup’`

**Comment by gordonwoodhull** [comment]
Cool. We'd still like to support `R CMD verb` installation of some sort so that we can put the package on rforge and also use some automated scripts which we have for installing packages on the Research lake.

**Comment by gordonwoodhull** [comment]
When I installed it using the above method, and tried to load the RCAP Designer, I got

```
Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: pubsub
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/requirejs-text/text.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: rcap/bower_components/requirejs-text/text
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/require-css/css.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: rcap/bower_components/require-css/css
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/parsleyjs/dist/parsley.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: parsley
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/datatables.net-buttons/js/buttons.html5.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: datatablesbuttons/buttons.html5.min
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/datatables.net/js/jquery.dataTables.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: datatables/jquery.dataTables.min
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/jquery.sparkline/dist/jquery.sparkline.min.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: jquery.sparkline/jquery.sparkline.min
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/select2/dist/js/select2.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: select2/js/select2
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/ionrangeslider/js/ion.rangeSlider.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: ionrangeslider/js/ion.rangeSlider
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/spectrum/spectrum.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: spectrum/spectrum
http://requirejs.org/docs/errors.html#scripterror
https://rcloud-2.research.att.com/shared.R/rcloud.rcap/bower_components/wysiwyg.js/dist/standalone.js Failed to load resource: the server responded with a status of 404 (Code 404)
require-common.js:65 Uncaught Error: Script error for: wysiwyg/standalone
http://requirejs.org/docs/errors.html#scripterror
```

**Comment by gaborcsardi** [comment]
`R CMD build` does not care about the build script failing and you end up with a broken package that is missing some files. 

This is hard (impossible?) to fix without changing `R CMD build`. Maybe the R code or a `configure` file could check if everything is there with some checksums.

**Comment by gordonwoodhull** [comment]
I see - thanks for the explanation. I guess our needs are satisfied by #144 for now.

**Comment by s-u** [comment]
The reason here is that the build step is done in `cleanup` which is run silently, i.e., it is allowed to fail. I guess the best way to fix this would be to add pre-flight script support to `build` in R.

**Comment by gaborcsardi** [comment]
Yes, this is what we discussed above, AFAIR. 

We could have the JS artifacts in the repo, and then we have no problems installing the package with standard R tools. That's fine with me, too. 

But if you want to 
1. avoid having `bower_components` in the repository, **and**
2. want to build & install with `R CMD build` or `devtools`, 
then AFAIK the best you can do is the `cleanup` script.

Or some kind of hack that checks if everything included, at install time. At install time, we can run whatever we want. This could be tricky, too, because a simple checksum might not be enough, since e.g. the SASS tools build slightly different css on different platforms and they are all "correct".
