### ISSUE TITLE
Create Accordion menu

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#48]
Add an Accordion drop down control item.

**Comment by NattyE** [comment]
Is this is same as #52?

**Comment by shaneporter** [comment]
Quite possibly.

**Comment by shaneporter** [comment]
In fact, I think this comes from the menu style we saw in ecomp, so I'll close the other one.

**Comment by shaneporter** [comment]
![image](https://cloud.githubusercontent.com/assets/2493614/19068857/361fd0dc-8a1c-11e6-88ef-d9b82f345da1.png)

**Comment by shaneporter** [comment]
- [ ] Create new accordion control
- [ ] The control's items will derive from the page hierarchy
- [ ] By default, child page items will not be shown. If the accordion menu is on a child page, its parent branches will be expanded; all other top level branches will be collapsed
- [ ] Items with children will show the item link as well as a link to open that item's children

**Comment by shaneporter** [comment]
Implemented in PR #168.
