### ISSUE TITLE
Create timer control

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#49]
Trigger after a selected amount of time without user intervention. This would be used as a refresh control for new data arrival (trigger data refresh at different frequencies like daily, hourly, etc. for data streaming) call this timer for streaming.

**Comment by paulinshek** [comment]
Closed, but a countdown is not displayed, which Mani said is okay (for now?). https://github.com/att/rcloud.rcap/wiki/Timer-in-RCAP explains how to use the timer control, since it needs a dummy variable
