### ISSUE TITLE
Create date range control

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#54]
Create a new control with start/end dates.

**Comment by NattyE** [comment]
With regards to

> Collect Start date and length

Should the start date and length return an end date from within the R backend or should we leave that for the user to calculate in the notebook using the interval length and interval type returned by the client side?

**Comment by NattyE** [comment]
This is now done. Please see wiki: https://github.com/att/rcloud.rcap/wiki/Using-dates-in-RCAP
