### ISSUE TITLE
Email reports

### ISSUE THREAD

**Issue by shaneporter** [att/rcloud.rcap#57]
Managers with an interest in information shown on an RCAP website/dashboard don't always want to log in on a periodic basis to see updates.

Add a feature so that a user can request that a page or control (specific example was 'data table') can be emailed to them (with updated information) on a periodic basis.

**Comment by paulinshek** [comment]
Additional request: image should be embedded in the email, rather than attached as an attachment.

**Comment by paulinshek** [comment]
https://github.com/MangoTheCat/email-screenshot/issues for things left to do

**Comment by gaborcsardi** [comment]
I am closing this here. New issues should go to the new repo.
