### ISSUE TITLE
Add js plots using HTML widgets

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#93]
Waiting for 2 js scripts.

**Comment by NattyE** [comment]
We have received the files from @statmkg but I am unsure what the actual request is. Having ran the notebook there are 4 plots and a table which all update when the filter changes. @statmkg is it that you'd like a widget that includes these 4 plots and the table in 1 single widget function?

**Comment by NattyE** [comment]
The widgets required are provided in the dcStockR (https://github.com/yutannihilation/dcStockR) package. This is a wrapper for the dc.js javascript library
