### ISSUE TITLE
htmlwidgets - slow load

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#98]
The HTMLWIDGET widgets take a long time to load when running the RCAP dashboard.

**Comment by NattyE** [comment]
I can definitely confirm this issue. Looking at the console, there is a JS warning referencing speed saying

    mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 

Which is referencing 

    d3.js:483:5

Other than that there are only issues about character encoding not being declared, a couple of deprecations and a few unreachable code after return statements but nothing that looks like it should affect `htmlwidget` performance.

**Comment by NattyE** [comment]
Ok digging a little more, there seems to be some form of continuous loop occurring. I recreated the notebook @statmkg sent me and did a performance recording. I have attached the results but essentially there are just continual repeats of `Incremental GC`, `MInor GC`, `CC Graph Reduction` and `Cycle Collection`. I understand this is to do with the containers resizing themselves?

**Comment by gordonwoodhull** [comment]
I don't know if GitHub issues take file attachments. 

This is really a question for @gaborcsardi, but I'll note that the D3 warning is quite normal.

HTML Widgets in core RCloud aren't *very* slow - most load in under 5s - but I do occasionally see loads taking 10s or more.

See
https://rcloud.social/edit.html?notebook=a45bcd38a6ffdc8c7e5c909cd8e145a1&version=946f1c78f9281702dbc33af5cfeb7954cf823084

and neighboring notebooks for comparison.

**Comment by NattyE** [comment]
Sorry, my PC crashed when trying to upload the file. I will speak with @gaborcsardi when he's back in next week :)

**Comment by dougmet** [comment]
is it a particular widget? Some of them are a bit bloaty.

**Comment by NattyE** [comment]
There are seemingly two issues going on here apparently.
1. The widgets take a long time to load. My instance of RCloud/RCAP are very slow and therefore the particular example I was sent still hadn't rendered the widgets after 20 minutes. However they do eventually render for Mani and Robert.
2. Widgets on other pages (not the landing page) of an RCAP dashboard never render. This is possibly something to do with the fact that the pages are hidden.

**Comment by gaborcsardi** [comment]
My bet would be that simply downloading the HTML of the iframe takes too long. Unfortunately we stick all included JS and HTML into the iframe, and everything is downloaded all the time. This is fine for small JS libs, but plotly is above 1MB AFAIR.

Anyway, we first need to measure what is slow.

**Comment by NattyE** [comment]
Interestingly this did work for me today though the widgets took a minute or two to load.

**Comment by gaborcsardi** [comment]
@NattyE That's probably your poor machine and your poor network.

**Comment by NattyE** [comment]
Talking with @statmkg it seems that these are similar load times for others too? But I agree that running RCloud on a VM probably isn't the best way to experiment...

**Comment by gaborcsardi** [comment]
@NattyE First of all, that notebook is a bit misleading, because everything is done in the same cell, so you are not "measuring" the loading time of the widget only. Something like this makes more sense:
https://gist.github.com/gaborcsardi/ecabf8b16aaffd2212ce2802baab8685

Ie. first cell:
```r
library(plotly)
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) +
            geom_bar(position = "dodge")
w <- ggplotly(p) 
```

Second cell:
```r
print(w)
```
and then only measure the execution of the second cell. I just did this six times, it took 17, 7, 5, 10, 3, 3 seconds, and I am on a poorish network, ~14 Mbps according to speedtest.net.

I can also confirm that ~100% of these times is taken by downloading the iframe of the widget from the R backend. 

So, yes, this can be improved, it is silly to download the full HTML + JS all the time. But it is also not entirely trivial, because so far we did not have to parse the HTML/JS of the widget at all, but now we'll have to.

**Comment by NattyE** [comment]
@gaborcsardi you have the wrong notebook.

**Comment by gaborcsardi** [comment]
@NattyE As far as I can see, there is only one notebook (link) in this thread. :)

**Comment by NattyE** [comment]
@gaborcsardi I have tagged you in the notebook on Dropbox. Let me know if you can see it - I know Shane had to alter my permissions.

**Comment by shaneporter** [comment]
Hopefully, you have access now @gaborcsardi - although I believe that anybody with edit permissions (does that include you @NattyE?)

**Comment by NattyE** [comment]
@shaneporter I can 13 files and one additional folder within the Mango folder

**Comment by gaborcsardi** [comment]
`Notebook 3.gist` is ~150KB, this is the smallest example we have? Also, it does not work for me:

```
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/home/nathan/Documents/notebooks/dcae_kpi_cldetail_draft_20160714call.RData', probable reason 'No such file or directory'
trace:
load(file = paste0(MetDir, "dcae_kpi_cldetail_draft_", MetFile, 
    ".RData"), envir = .GlobalEnv)
Get_Data(c(RngDate1, RngDate2), MetFile = MetVersion)
```

**Comment by gaborcsardi** [comment]
OK, the data file in the dropbox, but can we write this in a way that is portable? 

Also, after upgrading to the latest RCAP, I cannot open the designer, I get an error: 
```
Failed to load resource: the server responded with a status of 404 (Code 404)
http://127.0.0.1:8080/shared.R/rcloud.rcap/bower_components/jquery.sparkline/dist/jquery.sparkline.min.js
```

Can you load it at all?

**Comment by gaborcsardi** [comment]
Which branch and repo of `rcap` are we supposed to use now?

**Comment by gaborcsardi** [comment]
Anyway, forget it, I'll get it to work.

**Comment by gaborcsardi** [comment]
@gordonwoodhull  OK, here is a plan. We'll only send scripts (and data?) over once. On the client side, we store them in a dictionary. We use hashing to see if we need to send a script over or not.

For this we need to parse the HTML to find the tags that I want to extract and hash. Can I depend on the `xml2` package for the HTML parsing? Or does rcloud have a standard way to parse HTML on the server side?

Btw. it would be even better if I could serve the scripts from the server, over standard HTTP. Is there a standard rcloud way to do this?

**Comment by shaneporter** [comment]
Hi @gaborcsardi - we made rcap open source last week, so we should now be using the develop branch on AT&T.

**Comment by gaborcsardi** [comment]
@shaneporter got it working, thanks much!

**Comment by gordonwoodhull** [comment]
@gaborcsardi, I'm moving discussion to att/rcloud#2219, since this is really a core issue.

**Comment by gaborcsardi** [comment]
This was fixed in rcloud.
