### ISSUE TITLE
DataTables - more formatting controls

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#99]
* Numeric formats
* Colour coding of individual cells

**Comment by paulinshek** [comment]
need more information- how exaclty should the cells be coloured? how should this be specified by the user?

**Comment by NattyE** [comment]
These have now all been added in https://github.com/att/rcloud.rcap/commit/906f5ebbdeb1edc05d3d57be5b76b64cf478a801 and https://github.com/att/rcloud.rcap/commit/034294d338686a9d30093fb77b18467faf09f79f
